# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3aa72460-7d05-4bd4-861f-6ef8b82082dc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices = {
    cryptkey = {
      device = "/dev/disk/by-uuid/aaaa545f-b1f7-4861-8591-63812f28b31b";
    };
    cryptroot = {
      device = "/dev/disk/by-uuid/70fcf3f7-a862-422c-94bd-85ac1445768e";
      keyFile = "/dev/mapper/cryptkey";
    };
    cryptswap = {
      device = "/dev/disk/by-uuid/b2775928-e8cf-41ba-9fa7-be24e64e4579";
      keyFile = "/dev/mapper/cryptkey";
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2D03-B634";
      fsType = "vfat";
  };

  boot.initrd.postMountCommands = ''
    # Don't keep the cryptkey available all the time
    cryptsetup close /dev/mapper/cryptkey
  '';

  swapDevices =
    [ { device = "/dev/disk/by-uuid/102799bd-d9d2-4ef6-936f-6ba9b59f168e"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
