# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  networking.hostId = "a28d9fb2";
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mem_sleep_default=deep" ];

  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r tank/system/blank-root@blank
  '';

  fileSystems."/" =
    { device = "tank/system/blank-root";
      fsType = "zfs";
      options = [ "nosuid" ];
    };

  fileSystems."/home" =
    { device = "tank/user/home";
      fsType = "zfs";
      options = [ "nosuid" ];
    };

  fileSystems."/nix" =
    { device = "tank/local/nix";
      fsType = "zfs";
      options = [ "nosuid" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3A62-0D0D";
      fsType = "vfat";
      options = [ "nosuid" ];
    };

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
